import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Loading = () => (
  <main className="flex items-center flex-col">
    <h1>Loading...</h1>
  </main>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} bg-slate-100 dark:bg-slate-900 text-slate-500 dark:text-slate-400 min-h-screen`}>
        <div className="flex flex-col items-center">
          <h1>Makeplace price calculator</h1>
        </div>
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
